name: CI

on:
  push:
    branches: [main, master, hehe]
  pull_request:
    branches: [main, master, hehe]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        env:
          DATABASE_URL: postgresql://hekoti:hekoti@127.0.0.1:5432/hekoti?schema=public
        run: npm run build
